# -*- coding: utf-8 -*-
"""datascience_task4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YlruwG--7Lhgc8Ziy-F3Zf9EZ5zJejOB
"""

import pandas as pd
import numpy as np
from google.colab import files
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, classification_report

uploaded = files.upload()

import pandas as pd

# Load the dataset with ISO-8859-1 encoding
data = pd.read_csv('spam.csv', encoding='ISO-8859-1')

# Display the first few rows of the dataset
print(data.head())

data.describe()

print(data.isnull())

print(data.info())

print(data.isnull().sum())

data.rename(columns={'v1': 'label', 'v2': 'text'}, inplace=True)

data.describe()

data = data[['label', 'text']]

label_encoder = LabelEncoder()

data['label'] = label_encoder.fit_transform(data['label'])

X_train, X_test, y_train, y_test = train_test_split(data['text'], data['label'], test_size=0.2, random_state=42)

# Vectorize the text data using TF-IDF
tfidf_vectorizer = TfidfVectorizer(stop_words='english', max_df=0.7)
X_train_tfidf = tfidf_vectorizer.fit_transform(X_train)
X_test_tfidf = tfidf_vectorizer.transform(X_test)

nb_classifier = MultinomialNB()
nb_classifier.fit(X_train_tfidf, y_train)

y_pred = nb_classifier.predict(X_test_tfidf)

accuracy = accuracy_score(y_test, y_pred)
report = classification_report(y_test, y_pred)

print(f'Accuracy: {accuracy}')
print('Classification Report:')
print(report)